spring:
  application:
    name: crmsystem

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false  # <--- CRITICAL for development!
    prefix: classpath:/templates/
    suffix: .html

# Custom ELS Configuration
els:
  upload-dir: uploads # create an 'uploads' folder in project root

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#
#logging:
#  level:
#    org.flywaydb: DEBUG